---

- name: Enviar notificacion a Telegram
  community.general.telegram:
    token: "{{ token }}"
    api_args:
      chat_id: "{{ chat_id }}"
      parse_mode: "markdown"
      text: "Mensage de prueba"
      disable_web_page_preview: true
      disable_notification: true

...